apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: DevMindsCustomVPC
  region: eu-west-1

vpc:
  subnets:
    private:
      eu-west-1b: { id: subnet-08cc7694c91abab95 }
      eu-west-1c: { id: subnet-0f40119e51b0ca0fb }
      eu-west-1a: { id: subnet-01dc2dcca6d90c9bd }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: m5.xlarge
    desiredCapacity: 10
    privateNetworking: true
  - name: ng-2-builders
    labels: { role: builders }
    instanceType: m5.2xlarge
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true