apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: minikube-app4
spec: 
  replicas: 5 
  selector:
    matchLabels:
      app: minikube-app4
  template: 
    metadata: 
      labels: 
        app: minikube-app4
    spec: 
      containers: 
      - name: minikube-app4
        image: minikube-app4:1.5
        ports: 
        - containerPort: 80